domain: imkcp.xyz
title: imkcp
title_ext: 垃圾初中生

contacts:
  - icon: "fa fa-telegram"
    url: "https://t.me/cnimkcp"
    text: 与imkcp pm
  # - icon: "fa fa-wechat"
  #   text: 2088888812

domains:
  - domain: https://blog.imkcp.xyz/
    description: "imkcp的blog"
